services:
  - type: web
    name: voxmarket-backend
    env: node
    root: backend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        sync: false
    autoDeploy: false

  - type: static
    name: voxmarket-frontend
    env: static
    root: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: false
